services:
    towd:
        image: delnegend/towd:latest
        container_name: towd
        build:
            context: .
            dockerfile: Dockerfile
        pull_policy: never
        restart: unless-stopped
        ports:
            - 8080:8080
        volumes:
            - ./data:/app/data
        environment:
            SERVER_PORT: 8080
            DISCORD_GUILD_ID:
            DISCORD_APP_TOKEN:
            TIMEZONE:
            GROQ_API_KEY: